"""
AI Intelligence Pydantic Schemas
Problem Statement: SIH26155 (NTRO)
"""
from typing import Any, Dict, List, Optional
from pydantic import BaseModel, Field


class FindingExplanationResponse(BaseModel):
    summary: str = Field(..., description="High-level finding summary")
    why_it_matters: str = Field(..., description="Operational & security impact")
    technical_explanation: str = Field(..., description="In-depth technical analysis")
    risk_context: str = Field(..., description="Potential exploit/attack vectors")
    recommended_action: str = Field(..., description="Recommended vendor CLI remediation")
    confidence: float = Field(default=0.90, ge=0.0, le=1.0)
    evidence_used: List[str] = Field(default_factory=list)
    source_lines: List[int] = Field(default_factory=list)
    disclaimer: str = Field(
        default="AI-assisted explanation grounded in verified audit evidence. Verify CLI commands before applying."
    )


class RiskExplanationResponse(BaseModel):
    risk_id: str = Field(..., description="Deterministic Risk Identifier")
    title: str = Field(..., description="Risk Exposure Title")
    deterministic_risk_score: float = Field(..., description="Algorithmic risk score from deterministic engine")
    priority: str = Field(..., description="P0 / P1 / P2 / P3 priority band")
    why_this_risk_is_prioritized: str = Field(..., description="Technical rationale for prioritization")
    contributing_findings_analysis: List[str] = Field(default_factory=list, description="Analysis of contributing findings")
    attack_surface_analysis: str = Field(..., description="Exposure and vector analysis across device interfaces")
    business_operational_impact: str = Field(..., description="Potential threat actor impact if exploited")
    why_remediation_matters: str = Field(..., description="Security benefit of applying proposed remediation")
    confidence: float = Field(default=0.95, ge=0.0, le=1.0)
    disclaimer: str = Field(
        default="AI risk advisory grounded in deterministic finding metrics. Risk score is computed by static algorithm."
    )


class RemediationExplanationResponse(BaseModel):
    remediation_id: str = Field(..., description="Remediation Proposal Identifier")
    control_id: str = Field(..., description="Target Compliance Control ID")
    vendor: str = Field(..., description="Target Vendor (Cisco / Juniper / Fortinet)")
    what_changes: str = Field(..., description="Explanation of configuration directives being removed or added")
    why_change_is_safe: str = Field(..., description="Safety justification and why operational disruption is minimized")
    what_security_property_is_restored: str = Field(..., description="The exact compliance invariant restored")
    what_operator_should_verify: str = Field(..., description="Verification commands/steps for the operator post-change")
    confidence: float = Field(default=0.95, ge=0.0, le=1.0)
    disclaimer: str = Field(
        default="AI remediation advisory. CLI diff is strictly generated by static template catalog without automated push."
    )


class AuditAssistantQueryRequest(BaseModel):
    query: str = Field(..., min_length=2, max_length=500, description="Natural language question about the audit")
    audit_id: Optional[str] = Field(None, description="Audit session ID")


class AuditAssistantQueryResponse(BaseModel):
    query: str
    audit_id: str
    answer: str
    supporting_findings: List[str] = Field(
        default_factory=list, description="IDs or Control IDs of findings supporting this answer"
    )
    confidence: float = Field(default=0.95, ge=0.0, le=1.0)
    sources_count: int = 0


class UnknownConfigInterpretationRequest(BaseModel):
    raw_command: str = Field(..., min_length=1, max_length=1000)
    vendor_hint: str = Field(default="cisco")
    platform_hint: Optional[str] = None
    nearby_context: Optional[List[str]] = Field(default_factory=list)


class UnknownConfigInterpretationResponse(BaseModel):
    status: str = Field(default="candidate", description="'candidate' | 'uncertain' | 'unsupported'")
    normalized_category: str = Field(..., description="e.g. remote_access, authentication, logging")
    semantic_meaning: str = Field(..., description="Human-readable meaning of the command")
    candidate_property: Optional[str] = Field(None, description="Normalized field name candidate")
    candidate_value: Any = Field(None, description="Parsed canonical value")
    confidence: float = Field(..., ge=0.0, le=1.0)
    reasoning_summary: str = Field(..., description="Why the model selected this category")
    evidence: List[str] = Field(default_factory=list)
    alternative_interpretations: List[str] = Field(default_factory=list)
    confidence_tier: str = Field(default="review", description="'high' (>=0.90) | 'review' (0.70-0.89) | 'low' (<0.70)")
    disclaimer: Optional[str] = Field(default="AI candidate classification. Requires administrator approval and safety allowlist validation.")


class AIHealthResponse(BaseModel):
    provider: str
    model: str
    status: str
    has_api_key: bool
    temperature: float
    timeout_seconds: int
