"""
AI Intelligence Pydantic Schemas
Problem Statement: SIH26155 (NTRO)
"""
from typing import Any, Dict, List, Optional
from pydantic import BaseModel, Field


class FindingExplanationResponse(BaseModel):
    summary: str = Field(..., description="High-level finding summary")
    why_it_matters: str = Field(..., description="Operational & security impact")
    technical_explanation: str = Field(..., description="In-depth technical analysis")
    risk_context: str = Field(..., description="Potential exploit/attack vectors")
    recommended_action: str = Field(..., description="Recommended vendor CLI remediation")
    confidence: float = Field(default=0.90, ge=0.0, le=1.0)
    evidence_used: List[str] = Field(default_factory=list)
    source_lines: List[int] = Field(default_factory=list)
    disclaimer: str = Field(
        default="AI-assisted explanation grounded in verified audit evidence. Verify CLI commands before applying."
    )


class RiskExplanationResponse(BaseModel):
    risk_id: str = Field(..., description="Deterministic Risk Identifier")
    title: str = Field(..., description="Risk Exposure Title")
    deterministic_risk_score: float = Field(..., description="Algorithmic risk score from deterministic engine")
    priority: str = Field(..., description="P0 / P1 / P2 / P3 priority band")
    why_this_risk_is_prioritized: str = Field(..., description="Technical rationale for prioritization")
    contributing_findings_analysis: List[str] = Field(default_factory=list, description="Analysis of contributing findings")
    attack_surface_analysis: str = Field(..., description="Exposure and vector analysis across device interfaces")
    business_operational_impact: str = Field(..., description="Potential threat actor impact if exploited")
    why_remediation_matters: str = Field(..., description="Security benefit of applying proposed remediation")
    confidence: float = Field(default=0.95, ge=0.0, le=1.0)
    disclaimer: str = Field(
        default="AI risk advisory grounded in deterministic finding metrics. Risk score is computed by static algorithm."
    )


class RemediationExplanationResponse(BaseModel):
    remediation_id: str = Field(..., description="Remediation Proposal Identifier")
    control_id: str = Field(..., description="Target Compliance Control ID")
    vendor: str = Field(..., description="Target Vendor (Cisco / Juniper / Fortinet)")
    what_changes: str = Field(..., description="Explanation of configuration directives being removed or added")
    why_change_is_safe: str = Field(..., description="Safety justification and why operational disruption is minimized")
    what_security_property_is_restored: str = Field(..., description="The exact compliance invariant restored")
    what_operator_should_verify: str = Field(..., description="Verification commands/steps for the operator post-change")
    confidence: float = Field(default=0.95, ge=0.0, le=1.0)
    disclaimer: str = Field(
        default="AI remediation advisory. CLI diff is strictly generated by static template catalog without automated push."
    )


class AuditAssistantQueryRequest(BaseModel):
    query: str = Field(..., min_length=2, max_length=500, description="Natural language question about the audit")
    audit_id: Optional[str] = Field(None, description="Audit session ID")


class AuditAssistantQueryResponse(BaseModel):
    query: str
    audit_id: str
    answer: str
    supporting_findings: List[str] = Field(
        default_factory=list, description="IDs or Control IDs of findings supporting this answer"
    )
    confidence: float = Field(default=0.95, ge=0.0, le=1.0)
    sources_count: int = 0


class UnknownConfigInterpretationRequest(BaseModel):
    raw_command: str = Field(..., min_length=1, max_length=1000)
    vendor_hint: str = Field(default="cisco")
    platform_hint: Optional[str] = None
    nearby_context: Optional[List[str]] = Field(default_factory=list)


class UnknownConfigInterpretationResponse(BaseModel):
    status: str = Field(default="candidate", description="'candidate' | 'uncertain' | 'unsupported'")
    normalized_category: str = Field(..., description="e.g. remote_access, authentication, logging")
    semantic_meaning: str = Field(..., description="Human-readable meaning of the command")
    candidate_property: Optional[str] = Field(None, description="Normalized field name candidate")
    candidate_value: Any = Field(None, description="Parsed canonical value")
    confidence: float = Field(..., ge=0.0, le=1.0)
    reasoning_summary: str = Field(..., description="Why the model selected this category")
    evidence: List[str] = Field(default_factory=list)
    alternative_interpretations: List[str] = Field(default_factory=list)
    confidence_tier: str = Field(default="review", description="'high' (>=0.90) | 'review' (0.70-0.89) | 'low' (<0.70)")
    disclaimer: Optional[str] = Field(default="AI candidate classification. Requires administrator approval and safety allowlist validation.")


class AIHealthResponse(BaseModel):
    provider: str
    model: str
    status: str
    has_api_key: bool
    temperature: float
    timeout_seconds: int


class EvidenceCitation(BaseModel):
    control_id: str = Field(..., description="Target control identifier (e.g. CIS-1.2.1)")
    framework: str = Field(default="CIS", description="Framework name (CIS, NIST, STIG, ISO)")
    line_number: Optional[int] = Field(default=None, description="1-indexed configuration line number")
    evidence_snippet: Optional[str] = Field(default=None, description="Exact configuration evidence text")
    status: str = Field(default="FAIL", description="Deterministic compliance status (PASS / FAIL)")
    severity: str = Field(default="HIGH", description="Severity rating (CRITICAL, HIGH, MEDIUM, LOW)")
    title: Optional[str] = Field(default=None, description="Control or finding title")
    citation_label: str = Field(default="EVIDENCE", description="Formatted citation label (e.g. EVIDENCE · LINE 17)")


class TopRiskBriefItem(BaseModel):
    control_id: str = Field(..., description="Target control identifier")
    title: str = Field(..., description="Finding or control title")
    severity: str = Field(..., description="Finding severity")
    priority: str = Field(..., description="Deterministic priority band (P0 / P1 / P2 / P3)")
    why_it_matters: str = Field(..., description="Exploit scenario and technical impact")
    evidence_citation: Optional[EvidenceCitation] = Field(default=None, description="Grounded line-level citation")
    recommended_action: str = Field(..., description="Allowlisted remediation action command summary")
    actual_value: Optional[Any] = Field(default=None, description="Observed non-compliant value")
    expected_value: Optional[Any] = Field(default=None, description="Expected compliant state")


class SecurityEvolutionBrief(BaseModel):
    baseline_audit_id: str = Field(..., description="Reference baseline audit ID")
    current_audit_id: str = Field(..., description="Current audit ID")
    before_score: float = Field(..., description="Baseline compliance score %")
    after_score: float = Field(..., description="Remediated compliance score %")
    score_delta: float = Field(..., description="Compliance improvement delta %")
    risk_delta: float = Field(default=0.0, description="Risk score reduction points")
    resolved_count: int = Field(default=0, description="Number of resolved controls")
    regressed_count: int = Field(default=0, description="Number of regressed controls")
    resolved_controls_summary: List[str] = Field(default_factory=list, description="Resolved control IDs")
    regressed_controls_summary: List[str] = Field(default_factory=list, description="Regressed control IDs")
    narrative: str = Field(..., description="Executive narrative of security evolution")


class InvestigationOrderStep(BaseModel):
    step_number: int = Field(..., description="1-indexed step in the investigation checklist")
    control_id: str = Field(..., description="Target control ID to investigate")
    priority: str = Field(..., description="Deterministic priority (P0, P1, P2, P3)")
    action_summary: str = Field(..., description="What the security engineer should verify or configure")
    target_lines: List[int] = Field(default_factory=list, description="Source lines in configuration")
    reason: str = Field(..., description="Why this step is ordered at this priority")


class AISecurityBriefingRequest(BaseModel):
    audit_id: str = Field(..., description="Target audit session ID")
    baseline_audit_id: Optional[str] = Field(None, description="Optional baseline audit for time machine deltas")
    focus_area: Optional[str] = Field(default="ALL", description="Focus area ('CRITICAL_RISKS', 'COMPLIANCE_GAPS', 'EVOLUTION', 'ALL')")


class AISecurityBriefingResponse(BaseModel):
    advisory_only: bool = Field(default=True, description="Strict invariant that briefing is advisory-only")
    audit_id: str = Field(default="", description="Audit session ID")
    baseline_audit_id: Optional[str] = Field(None, description="Baseline audit ID if evolution compared")
    device_hostname: str = Field(default="Gateway-Node", description="Target asset hostname")
    detected_vendor: str = Field(default="cisco", description="Detected OS dialect (cisco, juniper, fortinet)")
    compliance_score: float = Field(default=0.0, description="Authoritative deterministic compliance score %")
    risk_score: float = Field(default=0.0, description="Authoritative deterministic algorithmic risk score")
    critical_p0_count: int = Field(default=0, description="Number of P0 / Critical exposures")
    high_p1_count: int = Field(default=0, description="Number of P1 / High exposures")
    posture_trend: str = Field(default="CRITICAL_ATTENTION_REQUIRED", description="Deterministic posture trend indicator")
    executive_summary: str = Field(default="Deterministic audit evaluation completed.", description="Executive overview grounded in deterministic findings")
    top_risks: List[TopRiskBriefItem] = Field(default_factory=list, description="Ranked top risks with evidence citations")
    security_evolution: Optional[SecurityEvolutionBrief] = Field(default=None, description="Security Time Machine evolution deltas")
    recommended_investigation_order: List[InvestigationOrderStep] = Field(default_factory=list, description="Deterministic priority-ordered checklist")
    suggested_copilot_questions: List[str] = Field(default_factory=list, description="Suggested follow-up analyst questions")
    grounded_evidence_citations: List[EvidenceCitation] = Field(default_factory=list, description="All grounded evidence citations used")
    model_used: str = Field(default="openrouter", description="Active AI model identifier")
    provider: str = Field(default="openrouter", description="AI gateway provider (openrouter or offline_standby)")
    limitations: str = Field(
        default="AI is ADVISORY only. Deterministic AST compliance decisions and risk scoring remain authoritative.",
        description="Explicit limitation disclaimer",
    )


class CopilotChatRequest(BaseModel):
    query: str = Field(..., min_length=2, max_length=500, description="Analyst question about the audit")
    audit_id: str = Field(..., description="Active audit session ID")
    baseline_audit_id: Optional[str] = Field(None, description="Optional baseline audit for time machine context")
    chat_history: Optional[List[Dict[str, str]]] = Field(default_factory=list, description="Prior conversation turns")


class CopilotChatResponse(BaseModel):
    advisory_only: bool = Field(default=True, description="Advisory-only marker")
    query: str = Field(default="", description="Echo of user prompt")
    audit_id: str = Field(default="", description="Active audit ID")
    answer: str = Field(default="", description="Evidence-grounded response with [EVIDENCE · LINE X] citations")
    grounded_evidence: List[EvidenceCitation] = Field(default_factory=list, description="Verified evidence citations")
    suggested_followups: List[str] = Field(default_factory=list, description="Contextual follow-up suggestions")
    model_used: str = Field(default="openrouter", description="Model used")
    disclaimer: str = Field(
        default="AI-assisted response grounded strictly in verified AST audit findings. Zero device write capability."
    )

